ackama/eslint-config-ackama

.eslintignore, .eslintplugin/index.js, .eslintplugin/prefer-valid-rules.ts, .eslintrc.js, package-lock.json, package.json, tsconfig.eslint.json
@rabid-dan finally came up with an excuse to make a custom ESRule :joy:
It's actually a pretty sweet one too: no ones actually made a quality tool to check for checking if a rule is deprecated, and ESLint's handling of invalid configurations is to just error at the first one - it's a pretty painful method of handling things.
At some point I'll probably break this out into it's own plugin, if not into the ESLint core itself.
=> chore: create `prefer-valid-rules` rule

flowtype.js, package-lock.json, package.json
🎉 
My flow is a bit rusty, so I'll run this against `theraces-react` when I've got a second, but we're leaning into TypeScript rather than Flow, so this is mainly useful for if we inherit another flow application.
=> feat: create `flowtype` config

package-lock.json, package.json, react.js
Look, it's the one that we've all been looking forward to! 🎉 
Since this is going to be the configuration that gets the most attention, I've focused initially on rules that cover general bugs & best practices that have straight-forward ways to action them.
I've also put a few rules that ideally we'd like as erroring to instead warn, as I feel they'll cause some waves.
I'm going to be running this over a few of our repos over the next couple of weeks to get a scope of how much of an impact it'll make, but it should be fine for completely new projects - It was based off what I used for the techweek lambda widget & another react project I've worked on a few months back, so it's very recent.
Finally, there will be some tweaking required for the overlap with Typescript. I've already turned off …
=> feat: create `react` config

.eslintplugin/prefer-valid-rules.ts, package-lock.json, package.json
[My PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41706) updating `@types/eslint` has been merged & published, so we don't need to argument the module ourselves.
=> chore: replace module argumentation with updated `@types/eslint`

.eslintplugin/prefer-valid-rules.ts, package.json
I didn't bump the actual version constraint for `@types/eslint`, and also forgot to pass `require` in the vm context for `prefer-valid-rules`.
The latter isn't needed unless `require` is actually used, which is why it didn't error in CI, but it's a nicity and I'm playing around with a new setup that'll use it so might as well just add it now and forget about it 🤷‍♂
=> Minor fixes

index.js
This allows you to have `/* eslint-disable <rule> */` at the top of a file without requiring an `eslint-enable` at the end; if anything is above the `eslint-disable`, then the `eslint-enable` *is* required.
This is useful for the rare times we want to disable a rule for an entire file, such as with `no-sync` in scripts.
=> fix(javascript): enable `allowWholeFile` for `disable-enable-pair`

.eslintignore, README.md
@Rabid-Dan, @mischa-s, @greg-parsons
I'll move this into Ackama tomorrow-ish, and include this in the setup cli as well once it's committed, but for now this'll do.
It's just chore commits, as there's no major value in having it released by itself - I've got `@typescript-eslint/naming-convention` setup that I'm going to commit in a few days that'll be a patch release anyway 🤷‍♂
=> chore: update `.eslintignore`

@typescript-eslint.js
I'm pretty happy with this now - I've checked it again relm & terra, and they're both pretty sweat.
I've left `@typescript-eslint/camelcase` enabled as it'll catch enough of the camelcase to gently nudge us without leaving us out to dry if we have a third-party library that requires camelcase, since we can disable it.
closes #12
=> Use typescript naming convention rule

.github/workflows/checks.yaml, .github/workflows/release.yaml, package.json
This speeds up tests by skipping type checking, which also tends to make for a nicer developer experience since you can run the tests without having to appease TypeScript.
=> Enable isolated modules

react.js
Turns out this is what they added in the 3.x.x major
=> chore(react): use `react-hooks/recommended`

@typescript-eslint.js
Having worked with this on for a bit, and done further research, I think for now it'll be better to have this off, as I believe it only really affects definitions that involve genetics while encouraging the opposite syntax to what is optimal in runtime code (aka classes), i.e:
```
interface Mx {
// good
myFunc1: () => void;
// bad
myFunc2(): void;
}
class Tx {
// good
doSomething1(): void {}
// bad
doSomething2: () => void;
}
```
This gets even more confusing when you start implementing interfaces:
```
interface Mx {
sayHello: () => void;
}
class Tx implements Mx {
sayHello(): void {}
}
```
Since the differences between using a method vs a property are subtle, I suspect a lot of people will understandably reach for a property when implementing such interfaces:
```
class Tx implements Mx { …
```
=> fix(@typescript-eslint): disable `method-signature-style`

.eslintplugin/no-deprecated-rules.ts, test/rules/no-deprecated-rules.spec.ts
Annoyingly I didn't rename the spec file when I renamed the rule :/
Also implemented suggestions to make things easier (saves me having to copy and paste the replacement names for deprecated rules).
I also realised that the tests for this were dependent on the actual package versions being used, meaning they'd become invalid when we updated - I've replaced them with a mock that returns a fake eslint plugin with a deprecated rule.
This should be applied to the tests for `prefer-valid-rules` as well at some point, but I'll do that later.
=> Update spec name

index.js
It's so rare to do an index import I didn't catch this until this afternoon :joy:
=> fix(javascript): group `index` with `parent` & `sibling` when ordering

@typescript-eslint.js, index.js
We actually want this left on, for class members:
```
class Mx {
// no lines required between these
p1: string;
p2: string;
// these require newlines in between
m1() {
//
}
m2() {
//
}
}
```
Technically this option lets you do `get g1() { return <value> }` which we don't want, but `prettier` prevents you from doing that.
=> Enable `exceptAfterSingleLine` option for `lines-between-class-members`

.eslintignore, .eslintrc.js, README.md, index.js, package.json
This is the special new feature, and allows us to drop `.eslintignore` completely in favor of baking it into the `.eslintrc.js` config.
It's still standard ignore syntax, just with each line represented by an item in the array.
The exciting part is that it means we can include it in the actual shared configurations, and in turn drop `.eslintignore.tt` from the rails template.
=> feat: use `ignorePatterns` in configs instead of `.eslintignore`

package-lock.json
This includes a patch fix for `eslint-plugin-eslint-config`, which is what is causing master to fail, and so preventing new releases.
=> chore: upgrade packages

package.json
This should be automated & tested for, but it's smallish fry as eslint will error without it anyway - I don't think this would even break yarn pnp 🤔 
The reason I'm doing it is that it's used to dynamically generate the `npm install --save-dev` line in the README.
=> fix: specify `eslint-plugin-import` as `peerDependencies`

index.js
Per https://github.com/eslint/eslint/issues/13560#issuecomment-672757418: 
> It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined.
Currently this prevents us from excluding specific files, i.e `!public/wp-admin`.
=> fix: don't ignore parent dirs, to allow for negation globs

@typescript-eslint.js
I missed this one when upgrading to v4
=> fix(@typescript-eslint): remove `interface-name-prefix` rule

.github/workflows/checks.yaml, .github/workflows/release.yaml
A few of these are needed due to changes in how GHA works (which is why #58 is failing).
=> ci: update actions to latest versions

.github/renovate.json
I think it'd be good to regenerate the lockfile on a ~monthly basis, just so we're up to date and in case anything changes in minor versions that we should know about.
This should hopefully do that, while maintaining semantic versioning constraints.
closes #62
=> ci: add `renovate` to regenerate lock file

.github/renovate.json
I figured this would happen - oh well.
=> ci: update `renovate` config to not pin dependencies

react.js
Me & @mischa-s have been talking and decided now that hooks are the mainstream way of doing react it makes less sense to have this at `error` level.
=> feat(react): make `jsx-no-bind` `warn` instead of `error`

package-lock.json, package.json
Renovate seems to be having a buggy week, and I didn't notice that it changed the peer dependency constraint for `eslint` in #85.
I've also "regenerated" the lockfile since it apparently was missing some hashes.
=> chore: restore eslint peer dependency constraint

README.md, flowtype.js, package-lock.json, package.json
Technically this should be a breaking change, but we're not actually using flow anywhere and we're not going to be doing a new major anytime soon so better to just get it changed now 🤷
=> fix(flowtype): switch to `@babel/eslint-parser`

index.js
In order to get prettier and eslint not conflicting over quote-props; 
https://github.com/ackama/prettier-config-ackama/blob/master/.prettierrc.json
The prettierrc specifies 
`
"quoteProps": "consistent"
`
but the default eslint rule for quote-props is "always", which conflicts with the specification of the prettierrc. In order to match the suggested code style in prettierrc, we need to update the eslint to the matching config of 'consistent-as-needed'
=> fix: bring quote props rule inline with prettier config

package-lock.json, package.json
This lets us drop the explicit use of `jest-circus`, as it's now the default 🎉
=> chore: update `jest` to v27

.github/renovate.json
This should hopefully reduce the amount of noise we get from Renovate when it tries to refresh the lockfile and for _some reason_ moves a bunch of dependencies literally back and forth between two places on the tree 🙄 
Specifically, this restricts it to being able to run between 1 hour of time, rather than ~5 hours (which is the default)
=> chore: reduce renovate noise

jest.js, test/configs.spec.ts
This is mainly to get #225 released, since `npm` v7+ doesn't let us install v26 without it.
I deprecated `no-if` in favor of `no-conditional-in-test`, as it's an improved version of the rule that checks for other kinds of conditional statements like switches and ternarys
=> fix(jest): switch to using `no-conditional-in-test` rule

.github/workflows/checks.yaml, .github/workflows/release.yaml, package-lock.json
This regenerates our lockfile using npm v7+, so it's now v2 - this will reduce noise in other PRs that change dependencies.
It also changes CI to use Node 16, so that we're using npm v7+
=> ci: use node 16 & npm v7+

.github/workflows/checks.yaml, .github/workflows/release.yaml
This is required by semantic release v20
=> ci: use Node 18

.github/CODEOWNERS
Our structure has changed so this group no longer exists
=> chore: remove codeowners file

package.json
```
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
<transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
}
```
=> chore: update deprecated `ts-jest` config

@typescript-eslint.js, flowtype.js, react.js, test/configs.spec.ts
`curly` is disabled by `eslint-config-prettier` as some of its configuration can conflict with Prettier; we enable it in our standard config in a way that is compatible but it's not in our tech-specific configs that do extend from `eslint-config-prettier` - since these configs are meant to come after our standard config, `curly` ends up getting completely disabled.
Because of how rules and configs currently work the main way to address this is by explicitly enabling the rule in each config - even though technically this rule isn't specific to the technologies each config is about, it's completely autofixable and I think it's reasonable to assume they'll be used with our standard config so I've gone with that.
This should not be needed once ESLint moves to using flat configs because we can …
=> fix: explicitly enable `curly` in configs that include `prettier`

.github/workflows/checks.yaml, .github/workflows/release.yaml, .npmrc
Strict engine checks are only for our CI - it doesn't impact consumers of the actual package, but will ensure updates like #302 will fail CI
=> ci: use Node v20 and enable strict engine checks

.github/workflows/checks.yaml, package.json
We're compatible with both of these versions:
- `@typescript-eslint` v7 is just dropping Node versions to align with ESLint v8/v9, to make it easier for the v8 major
- `eslint-plugin-jest` v28 is small, dropping some Node versions and removing a couple of deprecated things that we never used
For now I'm just making the smallest change possible to unblock some other unrelated work that involves NPM - I'm going to followup later with a bigger update which will include dropping support for the older versions.
=> fix: allow v7 of `@typescript-eslint` and v28 of `eslint-plugin-jest`

index.js
This reverts #101 which was never actually needed - for the most part having it configured is harmless since it matches our prettier config which in theory all of our codebases use, but if we ever have one that has a different [quote props](https://prettier.io/docs/en/options.html#quote-props) setting (e.g. due to an inherited codebase) then you have to deal with this.
Removing it's configuration just means one less place to stub your toe
=> fix: let `prettier` handle `quote-props`

test/configs.spec.ts, tools/generate-configs-list.ts
This should mean less thinking as we're going to start depending on more scoped packages soon as part of upgrading to ESLint v9 such as `@eslint-community/eslint-plugin-eslint-comments` and `@stylistic/eslint-plugin-{js,ts,react}`
=> chore: improve logic for determining package name for scoped plugins

test/configs.spec.ts
My pull request to `@types/eslint` adding this property got merged and released years ago so we've not needed this in a while 😅
=> test: remove unneeded module augmentation

README.md
While working on other stuff I realised these sections have some silly mistakes and still mention Semantic Pull Request which we've not used in a while so I decided to clean them up
=> docs: update releases and contributing sections

package-lock.json, package.json
This version adds support for ESLint v9 while being backwards compatible for us so we can allow both v4 and v5 at the same time.
[changelog is here](https://github.com/facebook/react/releases/tag/eslint-plugin-react-hooks%405.0.0)
=> feat: allow `eslint-plugin-react-hooks` v5

README.md, index.js, jest.js, react.js, typescript.js
Originally when I authored our configs I set a handful of rules to `warn` instead of `error` as a way of making the configs gentler and hint to people when it might be ok to actually disable the rule for that particular violation depending on the context.
In practice however, most people tend to expect the linter to block in CI and that if it doesn't then everything is fine, meaning the rules configured to `warn` were effectively the same as not being enabled at all except for when people run `--fix`.
When we've talked about this recently, the general consensus was people would prefer the rules just `error`, and so that's what this does
=> feat: make all rules `error` instead of `warn`
